# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-18 11:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector_of_attractions', '0002_auto_20181218_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='owner',
            field=models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
