# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 19:46
from __future__ import unicode_literals

import attractions.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[attractions.validators.validate_text])),
                ('category', models.CharField(choices=[('Monument', 'Monument'), ('Painting', 'Painting'), ('Church', 'Church'), ('Sculpture', 'Sculpture'), ('Museum', 'Museum')], max_length=20, validators=[attractions.validators.validate_category, attractions.validators.validate_text])),
                ('author', models.CharField(blank=True, max_length=120, null=True, validators=[attractions.validators.validate_text])),
                ('short_description', models.TextField(max_length=500, validators=[attractions.validators.validate_text])),
                ('long_description', models.TextField(blank=True, null=True, validators=[attractions.validators.validate_text])),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('upload', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AttractionAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('latitude', models.FloatField(max_length=20)),
                ('longitude', models.FloatField(max_length=20)),
                ('attraction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attractions.Attraction')),
            ],
        ),
        migrations.CreateModel(
            name='AttractionImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_pictures/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions.Attraction')),
            ],
        ),
        migrations.CreateModel(
            name='AttractionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('points', models.IntegerField()),
                ('is_dublicated', models.BooleanField(default=False)),
                ('attraction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attractions.Attraction')),
            ],
        ),
    ]
